//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreerideMTB_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Imagens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Imagens()
        {
            this.tbl_Produtos = new HashSet<tbl_Produtos>();
        }
    
        public int Id { get; set; }
        public string TituloImg { get; set; }
        public string Caminho { get; set; }
        public string Descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Produtos> tbl_Produtos { get; set; }
    }
}
