//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreerideMTB_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tbl_Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Produtos()
        {
            this.tbl_ProdutoEncomenda = new HashSet<tbl_ProdutoEncomenda>();
            this.tbl_Imagens = new HashSet<tbl_Imagens>();
        }
    
        public int Id_produto { get; set; }
        [RegularExpression(@"[\w\s'""()-.,:ªº]*")]
        [Required]
        public string Nome { get; set; }
        [AllowHtml]
        public string Descricao { get; set; }
        [Range(0, 10000)]
        [DataType(DataType.Currency)]
        public decimal Preco { get; set; }
        public int Categoria { get; set; }
        [Required]
        public Nullable<int> Sub_Categoria { get; set; }
        [Required]
        public Nullable<bool> Stock { get; set; }
        [Range(0, 500)]
        [Required]
        public Nullable<double> Peso { get; set; }
        public string SKU { get; set; }
        [Required]
        public Nullable<int> Marca { get; set; }
    
        public virtual tbl_Categoria tbl_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProdutoEncomenda> tbl_ProdutoEncomenda { get; set; }
        public virtual tbl_Sub_Categoria tbl_Sub_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Imagens> tbl_Imagens { get; set; }
        public virtual tbl_Marca tbl_Marca { get; set; }
    }
}
